name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Build and push image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flagflow:$GITHUB_SHA
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flagflow --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flagflow:$GITHUB_SHA --region ${{ secrets.GCP_REGION }} --platform managed --allow-unauthenticated
